---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "wonderwall-forward-auth.fullname" . }}
  labels:
    {{- include "wonderwall-forward-auth.labels" . | nindent 4 }}
data:
  WONDERWALL_OPENID_CLIENT_SECRET: "{{ .Values.openid.clientSecret | required ".Values.openid.clientSecret is required." | b64enc }}"
  WONDERWALL_ENCRYPTION_KEY: "{{ .Values.session.cookieEncryptionKey | required ".Values.session.cookieEncryptionKey is required." | b64enc }}"
  WONDERWALL_REDIS_PASSWORD: "{{ .Values.valkey.password | required ".Values.valkey.password is required." | b64enc }}"
