---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "wonderwall-forward-auth.fullname" . }}
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{- include "wonderwall-forward-auth.labels" . | nindent 4 }}
stringData:
  WONDERWALL_BIND_ADDRESS: "0.0.0.0:8080"
  WONDERWALL_COOKIE_SAME_SITE: "None"
  WONDERWALL_METRICS_BIND_ADDRESS: "0.0.0.0:8081"
  WONDERWALL_INGRESS: "https://{{ .Values.sso.domain }}"
  WONDERWALL_SHUTDOWN_WAIT_BEFORE_PERIOD: "5s"
  WONDERWALL_OPENID_PROVIDER: "openid"
  WONDERWALL_OPENID_CLIENT_ID: "{{ .Values.openid.clientID | required ".Values.openid.clientID is required." }}"
  WONDERWALL_OPENID_CLIENT_SECRET: "{{ .Values.openid.clientSecret | required ".Values.openid.clientSecret is required." }}"
  WONDERWALL_OPENID_WELL_KNOWN_URL: "{{ .Values.openid.wellKnownURL | required ".Values.openid.wellKnownURL is required." }}"
  WONDERWALL_ENCRYPTION_KEY: "{{ .Values.session.cookieEncryptionKey | required ".Values.session.cookieEncryptionKey is required." }}"
  WONDERWALL_REDIS_URI: "redis://{{ .Values.valkey.fullnameOverride }}-primary:6379"
  WONDERWALL_REDIS_USERNAME: "default"
  WONDERWALL_SESSION_MAX_LIFETIME: "{{ .Values.session.maxLifetime | required ".Values.session.maxLifetime is required." }}"
  WONDERWALL_SESSION_FORWARD_AUTH: "true"
  WONDERWALL_SESSION_INACTIVITY: "{{ .Values.session.inactivity | required ".Values.session.inactivity is required." }}"
  WONDERWALL_SESSION_INACTIVITY_TIMEOUT: "{{ .Values.session.inactivityTimeout | required ".Values.session.inactivityTimeout is required." }}"
  WONDERWALL_SSO_DOMAIN: "{{ .Values.sso.domain | required ".Values.sso.domain is required." }}"
  WONDERWALL_SSO_ENABLED: "true"
  WONDERWALL_SSO_MODE: "server"
  WONDERWALL_SSO_SESSION_COOKIE_NAME: "{{ .Values.session.cookieName | required ".Values.session.cookieName is required." }}"
  WONDERWALL_SSO_SERVER_DEFAULT_REDIRECT_URL: "{{ .Values.sso.defaultRedirectURL | required ".Values.sso.defaultRedirectURL is required." }}"
