---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "wonderwall-forward-auth.labels" . | nindent 4 }}
  name: {{ include "wonderwall-forward-auth.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: http-metrics
      port: 8081
      protocol: TCP
      targetPort: http-metrics
  selector:
    {{- include "wonderwall-forward-auth.selectorLabels" . | nindent 4 }}
