services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  otel:
    image: grafana/otel-lgtm:latest
    ports:
      - "3002:3000"
      - "4317:4317"
      - "4318:4318"
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.8
    ports:
      - "8888:8080"
    environment:
      JSON_CONFIG: "{\"interactiveLogin\":false}"
  upstream:
    image: mendhak/http-https-echo:30
    ports:
      - "4000:4000"
    environment:
      HTTP_PORT: 4000
      JWT_HEADER: Authorization
      LOG_IGNORE_PATH: /
