package openid

const (
	ACRValues             = "acr_values"
	ClientAssertion       = "client_assertion"
	ClientAssertionType   = "client_assertion_type"
	ClientID              = "client_id"
	CodeChallenge         = "code_challenge"
	CodeChallengeMethod   = "code_challenge_method"
	Code                  = "code"
	CodeVerifier          = "code_verifier"
	Error                 = "error"
	ErrorDescription      = "error_description"
	GrantType             = "grant_type"
	IDTokenHint           = "id_token_hint"
	Nonce                 = "nonce"
	PostLogoutRedirectURI = "post_logout_redirect_uri"
	SessionState          = "session_state"
	Sid                   = "sid"
	State                 = "state"
	RedirectURI           = "redirect_uri"
	RefreshToken          = "refresh_token"
	Resource              = "resource"
	ResponseMode          = "response_mode"
	UILocales             = "ui_locales"
)
