nameOverride: ""
fullnameOverride: ""

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/wonderwall
  tag: latest

# mapped by fasit
fasit:
  tenant:
    name:

resources:
  limits:
    cpu: "2"
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 64Mi
replicas:
  min: 2
  max: 4
podDisruptionBudget:
  maxUnavailable: 1
ingressClassName: nais-ingress-fa
otel:
  endpoint: http://opentelemetry-management-collector.nais-system:4317

openid:
  clientID:
  clientSecret:
  extraAudience:
  extraScopes:
  wellKnownURL: https://auth.nais.io/.well-known/openid-configuration
session:
  maxLifetime: 10h
  # 256 bits key, in standard base64 encoding
  cookieEncryptionKey:
  cookieName: nais-io-forward-auth
sso:
  defaultRedirectURL:
  domain:

valkey:
  fullnameOverride: "wonderwall-forward-auth-valkey"
  architecture: "standalone"
  primary:
    resourcesPreset: "medium"
    persistence:
      enabled: false
  networkPolicy:
    enabled: true
    allowExternal: false
    allowExternalEgress: false
