{{- if and .Values.azure.enabled .Values.azure.forwardAuth.enabled }}
---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: {{ include "wonderwall.fullname" . }}-fa
  labels:
    {{- include "wonderwall.labelsForwardAuth" . | nindent 4 }}
spec:
  secretName: {{ .Values.azure.forwardAuth.clientSecretName }}
  allowAllUsers: true
  logoutUrl: "{{ include "wonderwall.azure.forwardAuthURL" . }}/oauth2/logout/frontchannel"
  replyUrls:
    - url: "{{- include "wonderwall.azure.forwardAuthURL" . }}/oauth2/callback"
  tenant: nav.no
{{- end }}
