{{- if and .Values.azure.enabled .Values.azure.forwardAuth.enabled }}
---
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  {{- if .Values.resourceSuffix }}
  name: {{ include "wonderwall.fullname" . }}-fa-{{ .Values.resourceSuffix }}
  {{- else }}
  name: {{ include "wonderwall.fullname" . }}-fa
  {{- end }}
  labels:
    {{- include "wonderwall.labelsForwardAuth" . | nindent 4 }}
spec:
  secretName: {{ .Values.azure.forwardAuth.clientSecretName }}
  allowAllUsers: true
  {{- if .Values.azure.forwardAuth.groupIds }}
  claims:
    groups:
      {{- range .Values.azure.forwardAuth.groupIds }}
      - id: {{ . }}
      {{- end }}
  {{- end }}
  logoutUrl: "{{ include "wonderwall.azure.forwardAuthURL" . }}/oauth2/logout/frontchannel"
  replyUrls:
    - url: "{{- include "wonderwall.azure.forwardAuthURL" . }}/oauth2/callback"
  tenant: nav.no
{{- end }}
