{{- if and .Values.azure.enabled .Values.azure.forwardAuth.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/search: "true"
  labels:
    aiven: enabled
    azure: enabled
  name: {{ include "wonderwall.fullname" . }}-fa
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "wonderwall.selectorLabelsForwardAuth" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: wonderwall-fa
        prometheus.io/path: /
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        checksum/secret: {{ pick ( include (print $.Template.BasePath "/fa-secret.yaml") . | fromYaml ) "data" | toYaml | sha256sum }}
      labels:
        aiven: enabled
        azure: enabled
        {{- include "wonderwall.labelsForwardAuth" . | nindent 8 }}
      name: wonderwall-fa
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - "{{ include "wonderwall.name" . }}"
                topologyKey: kubernetes.io/hostname
              weight: 10
      containers:
        - env:
          - name: OTEL_SERVICE_NAME
            value: wonderwall-fa
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{ .Values.otel.endpoint }}
          - name: WONDERWALL_BIND_ADDRESS
            value: "0.0.0.0:8080"
          - name: WONDERWALL_COOKIE_SAME_SITE
            value: "None"
          - name: WONDERWALL_METRICS_BIND_ADDRESS
            value: "0.0.0.0:8081"
          - name: WONDERWALL_INGRESS
            value: "{{- include "wonderwall.azure.forwardAuthURL" . }}"
          - name: WONDERWALL_SHUTDOWN_WAIT_BEFORE_PERIOD
            value: "5s"
          - name: WONDERWALL_OPENID_PROVIDER
            value: "azure"
          - name: WONDERWALL_REDIS_CONNECTION_IDLE_TIMEOUT
            value: "{{ .Values.redis.connectionIdleTimeout }}"
          - name: WONDERWALL_SESSION_MAX_LIFETIME
            value: "{{ .Values.azure.sessionMaxLifetime | required ".Values.azure.forwardAuth.sessionMaxLifetime is required." }}"
          - name: WONDERWALL_SESSION_FORWARD_AUTH
            value: "true"
          - name: WONDERWALL_SSO_DOMAIN
            value: "{{ .Values.azure.forwardAuth.ssoDomain | required ".Values.azure.forwardAuth.ssoDomain is required." }}"
          - name: WONDERWALL_SSO_ENABLED
            value: "true"
          - name: WONDERWALL_SSO_MODE
            value: "server"
          - name: WONDERWALL_SSO_SESSION_COOKIE_NAME
            value: "{{ .Values.azure.forwardAuth.sessionCookieName | required ".Values.azure.forwardAuth.sessionCookieName is required." }}"
          - name: WONDERWALL_SSO_SERVER_DEFAULT_REDIRECT_URL
            value: "{{ .Values.azure.forwardAuth.ssoDefaultRedirectURL | required ".Values.azure.forwardAuth.ssoDefaultRedirectURL is required." }}"
          - name: WONDERWALL_REDIS_URI
            valueFrom:
              secretKeyRef:
                {{- if .Values.resourceSuffix }}
                key: "REDIS_URI_WONDERWALL_AZURE_{{ .Values.resourceSuffix | upper }}"
                {{- else }}
                key: REDIS_URI_WONDERWALL_AZURE
                {{- end }}
                name: {{ .Values.azure.redisSecretName }}
          - name: WONDERWALL_REDIS_USERNAME
            valueFrom:
              secretKeyRef:
                {{- if .Values.resourceSuffix }}
                key: "REDIS_USERNAME_WONDERWALL_AZURE_{{ .Values.resourceSuffix | upper }}"
                {{- else }}
                key: REDIS_USERNAME_WONDERWALL_AZURE
                {{- end }}
                name: {{ .Values.azure.redisSecretName }}
          - name: WONDERWALL_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.resourceSuffix }}
                key: "REDIS_PASSWORD_WONDERWALL_AZURE_{{ .Values.resourceSuffix | upper }}"
                {{- else }}
                key: REDIS_PASSWORD_WONDERWALL_AZURE
                {{- end }}
                name: {{ .Values.azure.redisSecretName }}
          envFrom:
            - secretRef:
                name: "{{ .Values.azure.forwardAuth.clientSecretName }}"
            - secretRef:
                name: "{{ .Values.azure.forwardAuth.ssoServerSecretName }}"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /oauth2/ping
              port: http
          name: wonderwall-fa
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /oauth2/ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1069
            runAsNonRoot: true
            runAsUser: 1069
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: writable-tmp
      dnsPolicy: ClusterFirst
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "wonderwall.fullname" . }}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: writable-tmp
{{- end }}
