{{- if and .Values.azure.enabled .Values.azure.forwardAuth }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
    prometheus.io/path: /oauth2/ping
    prometheus.io/scrape: "true"
  labels:
    {{- include "wonderwall.labelsForwardAuth" . | nindent 4 }}
  name: {{ include "wonderwall.fullname" . }}-fa
spec:
  ingressClassName: {{ .Values.azure.forwardAuth.ingressClassName }}
  rules:
    - host: {{ .Values.azure.forwardAuth.ssoDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "wonderwall.fullname" . }}-fa
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
{{- end }}
