{{- if and .Values.azure.enabled .Values.azure.forwardAuth.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "wonderwall.labelsForwardAuth" . | nindent 4 }}
  name: {{ include "wonderwall.fullname" . }}-fa
spec:
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "wonderwall.selectorLabelsForwardAuth" . | nindent 6 }}
{{- end }}
