{{- if and .Values.azure.enabled .Values.azure.forwardAuth.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: "{{ .Values.azure.forwardAuth.ssoServerSecretName }}"
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{- include "wonderwall.labelsForwardAuth" . | nindent 4 }}
data:
  WONDERWALL_ENCRYPTION_KEY: "{{ .Values.azure.forwardAuth.sessionCookieEncryptionKey | required ".Values.azure.forwardAuth.sessionCookieEncryptionKey is required." | b64enc }}"
{{- end }}
