{{ if .Values.azure.forwardAuth }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: "{{ .Values.azure.ssoServerSecretName }}"
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{- include "wonderwall.labels" . | nindent 4 }}
stringData:
  WONDERWALL_BIND_ADDRESS: "0.0.0.0:8080"
  WONDERWALL_METRICS_BIND_ADDRESS: "0.0.0.0:8081"
  WONDERWALL_INGRESS: "{{- include "wonderwall.azure.ssoServerURL" . }}"
  WONDERWALL_SHUTDOWN_WAIT_BEFORE_PERIOD: "5s"
  WONDERWALL_OPENID_PROVIDER: "azure"
  WONDERWALL_REDIS_CONNECTION_IDLE_TIMEOUT: "{{ .Values.redis.connectionIdleTimeout }}"
  WONDERWALL_ENCRYPTION_KEY: "{{ .Values.azure.sessionCookieEncryptionKey | required ".Values.azure.sessionCookieEncryptionKey is required." }}"
  WONDERWALL_SESSION_MAX_LIFETIME: "{{ .Values.azure.sessionMaxLifetime | required ".Values.azure.sessionMaxLifetime is required." }}"
  WONDERWALL_SESSION_REFRESH: "false"
  WONDERWALL_SESSION_REFRESH_AUTO: "false"
  WONDERWALL_SSO_DOMAIN: "{{ .Values.azure.ssoDomain | required ".Values.azure.ssoDomain is required." }}"
  WONDERWALL_SSO_ENABLED: "true"
  WONDERWALL_SSO_MODE: "server"
  WONDERWALL_SSO_SESSION_COOKIE_NAME: "{{ .Values.azure.sessionCookieName | required ".Values.azure.sessionCookieName is required." }}"
  WONDERWALL_SSO_SERVER_DEFAULT_REDIRECT_URL: "{{ .Values.azure.ssoDefaultRedirectURL | required ".Values.azure.ssoDefaultRedirectURL is required." }}"
{{ end }}
