{{- if and .Values.azure.enabled .Values.azure.forwardAuth.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: "{{ .Values.azure.forwardAuth.ssoServerSecretName }}"
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{- include "wonderwall.labelsForwardAuth" . | nindent 4 }}
stringData:
  WONDERWALL_BIND_ADDRESS: "0.0.0.0:8080"
  WONDERWALL_COOKIE_SAME_SITE: "None"
  WONDERWALL_METRICS_BIND_ADDRESS: "0.0.0.0:8081"
  WONDERWALL_INGRESS: "{{- include "wonderwall.azure.forwardAuthURL" . }}"
  WONDERWALL_SHUTDOWN_WAIT_BEFORE_PERIOD: "5s"
  WONDERWALL_OPENID_PROVIDER: "azure"
  WONDERWALL_REDIS_CONNECTION_IDLE_TIMEOUT: "{{ .Values.redis.connectionIdleTimeout }}"
  WONDERWALL_ENCRYPTION_KEY: "{{ .Values.azure.forwardAuth.sessionCookieEncryptionKey | required ".Values.azure.forwardAuth.sessionCookieEncryptionKey is required." }}"
  WONDERWALL_SESSION_MAX_LIFETIME: "{{ .Values.azure.sessionMaxLifetime | required ".Values.azure.forwardAuth.sessionMaxLifetime is required." }}"
  WONDERWALL_SESSION_FORWARD_AUTH: "true"
  WONDERWALL_SESSION_INACTIVITY: "{{ .Values.azure.forwardAuth.sessionInactivity | required ".Values.azure.forwardAuth.sessionInactivity is required." }}"
  WONDERWALL_SESSION_INACTIVITY_TIMEOUT: "{{ .Values.azure.forwardAuth.sessionInactivityTimeout | required ".Values.azure.forwardAuth.sessionInactivityTimeout is required." }}"
  WONDERWALL_SSO_DOMAIN: "{{ .Values.azure.forwardAuth.ssoDomain | required ".Values.azure.forwardAuth.ssoDomain is required." }}"
  WONDERWALL_SSO_ENABLED: "true"
  WONDERWALL_SSO_MODE: "server"
  WONDERWALL_SSO_SESSION_COOKIE_NAME: "{{ .Values.azure.forwardAuth.sessionCookieName | required ".Values.azure.forwardAuth.sessionCookieName is required." }}"
  WONDERWALL_SSO_SERVER_DEFAULT_REDIRECT_URL: "{{ .Values.azure.forwardAuth.ssoDefaultRedirectURL | required ".Values.azure.forwardAuth.ssoDefaultRedirectURL is required." }}"
{{- end }}
