{{- if .Values.idporten.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "wonderwall.labelsIdporten" . | nindent 4 }}
  name: {{ include "wonderwall.fullname" . }}-idporten
spec:
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
  selector:
    matchLabels:
      {{- include "wonderwall.selectorLabelsIdporten" . | nindent 6 }}
{{- end }}
