{{- if .Values.idporten.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/search: "true"
  labels:
    aiven: enabled
    idporten: enabled
    {{- include "wonderwall.labelsIdporten" . | nindent 4 }}
  name: {{ include "wonderwall.fullname" . }}-idporten
spec:
  progressDeadlineSeconds: 300
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "wonderwall.selectorLabelsIdporten" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: wonderwall-idporten
        prometheus.io/path: /
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        checksum/secret: {{ pick ( include (print $.Template.BasePath "/idporten-secret.yaml") . | fromYaml ) "data" | toYaml | sha256sum }}
      labels:
        aiven: enabled
        idporten: enabled
        {{- include "wonderwall.labelsIdporten" . | nindent 8 }}
      name: wonderwall-idporten
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - "{{ include "wonderwall.name" . }}"
                topologyKey: kubernetes.io/hostname
              weight: 10
      containers:
        - env:
          - name: OTEL_SERVICE_NAME
            value: wonderwall-idporten
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{ .Values.otel.endpoint }}
          - name: WONDERWALL_BIND_ADDRESS
            value: "0.0.0.0:8080"
          - name: WONDERWALL_METRICS_BIND_ADDRESS
            value: "0.0.0.0:8081"
          - name: WONDERWALL_INGRESS
            value: "{{- include "wonderwall.idporten.ssoServerURL" . }}"
          - name: WONDERWALL_SHUTDOWN_WAIT_BEFORE_PERIOD
            value: "5s"
          - name: WONDERWALL_LEGACY_COOKIE
            value: "{{ .Values.idporten.legacyCookie }}"
          - name: WONDERWALL_OPENID_ACR_VALUES
            value: "{{ .Values.idporten.openidAcrValues | required ".Values.idporten.openidAcrValues is required." }}"
          - name: WONDERWALL_OPENID_LOCALE
            value: "{{ .Values.idporten.openidLocale | required ".Values.idporten.openidLocale is required." }}"
          - name: WONDERWALL_OPENID_POST_LOGOUT_REDIRECT_URI
            value: "{{ .Values.idporten.openidPostLogoutRedirectURL | required ".Values.idporten.postLogoutRedirectURL is required." }}"
          - name: WONDERWALL_OPENID_PROVIDER
            value: "idporten"
          - name: WONDERWALL_OPENID_RESOURCE_INDICATOR
            value: "{{ .Values.idporten.openidResourceIndicator | required ".Values.idporten.openidResourceIndicator is required." }}"
          - name: WONDERWALL_REDIS_CONNECTION_IDLE_TIMEOUT
            value: "{{ .Values.redis.connectionIdleTimeout }}"
          - name: WONDERWALL_SESSION_INACTIVITY
            value: "{{ .Values.idporten.sessionInactivity | required ".Values.idporten.sessionInactivity is required." }}"
          - name: WONDERWALL_SESSION_INACTIVITY_TIMEOUT
            value: "{{ .Values.idporten.sessionInactivityTimeout | required ".Values.idporten.sessionInactivityTimeout is required." }}"
          - name: WONDERWALL_SESSION_MAX_LIFETIME
            value: "{{ .Values.idporten.sessionMaxLifetime | required ".Values.idporten.sessionMaxLifetime is required." }}"
          - name: WONDERWALL_SSO_DOMAIN
            value: "{{ .Values.idporten.ssoDomain | required ".Values.idporten.ssoDomain is required." }}"
          - name: WONDERWALL_SSO_ENABLED
            value: "true"
          - name: WONDERWALL_SSO_MODE
            value: "server"
          - name: WONDERWALL_SSO_SESSION_COOKIE_NAME
            value: "{{ .Values.idporten.sessionCookieName | required ".Values.idporten.sessionCookieName is required." }}"
          - name: WONDERWALL_SSO_SERVER_DEFAULT_REDIRECT_URL
            value: "{{ .Values.idporten.ssoDefaultRedirectURL | required ".Values.idporten.ssoDefaultRedirectURL is required." }}"
          - name: WONDERWALL_REDIS_URI
            valueFrom:
              secretKeyRef:
                {{- if .Values.resourceSuffix }}
                key: "REDIS_URI_WONDERWALL_IDPORTEN_{{ .Values.resourceSuffix | upper }}"
                {{- else }}
                key: REDIS_URI_WONDERWALL_IDPORTEN
                {{- end }}
                name: {{ .Values.idporten.redisSecretNames.readwrite }}
          - name: WONDERWALL_REDIS_USERNAME
            valueFrom:
              secretKeyRef:
                {{- if .Values.resourceSuffix }}
                key: "REDIS_USERNAME_WONDERWALL_IDPORTEN_{{ .Values.resourceSuffix | upper }}"
                {{- else }}
                key: REDIS_USERNAME_WONDERWALL_IDPORTEN
                {{- end }}
                name: {{ .Values.idporten.redisSecretNames.readwrite }}
          - name: WONDERWALL_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if .Values.resourceSuffix }}
                key: "REDIS_PASSWORD_WONDERWALL_IDPORTEN_{{ .Values.resourceSuffix | upper }}"
                {{- else }}
                key: REDIS_PASSWORD_WONDERWALL_IDPORTEN
                {{- end }}
                name: {{ .Values.idporten.redisSecretNames.readwrite }}
          envFrom:
            - secretRef:
                name: "{{ .Values.idporten.clientSecretName }}"
            - secretRef:
                name: "{{ .Values.idporten.ssoServerSecretName }}"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /oauth2/ping
              port: http
          name: wonderwall-idporten
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /oauth2/ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1069
            runAsNonRoot: true
            runAsUser: 1069
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: writable-tmp
      dnsPolicy: ClusterFirst
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "wonderwall.fullname" . }}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: writable-tmp
{{- end }}
