{{ if .Values.idporten.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: "{{ .Values.idporten.ssoServerSecretName }}"
  annotations:
    reloader.stakater.com/match: "true"
  labels:
    {{- include "wonderwall.labelsIdporten" . | nindent 4 }}
stringData:
  WONDERWALL_BIND_ADDRESS: "0.0.0.0:8080"
  WONDERWALL_METRICS_BIND_ADDRESS: "0.0.0.0:8081"
  WONDERWALL_INGRESS: "{{- include "wonderwall.idporten.ssoServerURL" . }}"
  WONDERWALL_SHUTDOWN_WAIT_BEFORE_PERIOD: "5s"
  WONDERWALL_LEGACY_COOKIE: "{{ .Values.idporten.legacyCookie }}"
  WONDERWALL_OPENID_ACR_VALUES: "{{ .Values.idporten.openidAcrValues | required ".Values.idporten.openidAcrValues is required." }}"
  WONDERWALL_OPENID_LOCALE: "{{ .Values.idporten.openidLocale | required ".Values.idporten.openidLocale is required." }}"
  WONDERWALL_OPENID_POST_LOGOUT_REDIRECT_URI: "{{ .Values.idporten.openidPostLogoutRedirectURL | required ".Values.idporten.postLogoutRedirectURL is required." }}"
  WONDERWALL_OPENID_PROVIDER: "idporten"
  WONDERWALL_OPENID_RESOURCE_INDICATOR: "{{ .Values.idporten.openidResourceIndicator | required ".Values.idporten.openidResourceIndicator is required." }}"
  WONDERWALL_REDIS_CONNECTION_IDLE_TIMEOUT: "{{ .Values.redis.connectionIdleTimeout }}"
  WONDERWALL_ENCRYPTION_KEY: "{{ .Values.idporten.sessionCookieEncryptionKey | required ".Values.idporten.sessionCookieEncryptionKey is required." }}"
  WONDERWALL_SESSION_INACTIVITY: "{{ .Values.idporten.sessionInactivity | required ".Values.idporten.sessionInactivity is required." }}"
  WONDERWALL_SESSION_INACTIVITY_TIMEOUT: "{{ .Values.idporten.sessionInactivityTimeout | required ".Values.idporten.sessionInactivityTimeout is required." }}"
  WONDERWALL_SESSION_MAX_LIFETIME: "{{ .Values.idporten.sessionMaxLifetime | required ".Values.idporten.sessionMaxLifetime is required." }}"
  WONDERWALL_SESSION_REFRESH: "{{ .Values.idporten.sessionRefresh | required ".Values.idporten.sessionRefresh is required." }}"
  WONDERWALL_SESSION_REFRESH_AUTO: "false"
  WONDERWALL_SSO_DOMAIN: "{{ .Values.idporten.ssoDomain | required ".Values.idporten.ssoDomain is required." }}"
  WONDERWALL_SSO_ENABLED: "true"
  WONDERWALL_SSO_MODE: "server"
  WONDERWALL_SSO_SESSION_COOKIE_NAME: "{{ .Values.idporten.sessionCookieName | required ".Values.idporten.sessionCookieName is required." }}"
  WONDERWALL_SSO_SERVER_DEFAULT_REDIRECT_URL: "{{ .Values.idporten.ssoDefaultRedirectURL | required ".Values.idporten.ssoDefaultRedirectURL is required." }}"
{{ end }}
