{{ if .Values.idporten.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: "{{ .Values.idporten.ssoServerSecretName }}"
  labels:
    {{- include "wonderwall.labelsIdporten" . | nindent 4 }}
data:
  WONDERWALL_ENCRYPTION_KEY: "{{ .Values.idporten.sessionCookieEncryptionKey | required ".Values.idporten.sessionCookieEncryptionKey is required." | b64enc }}"
{{ end }}
