{{ if .Values.idporten.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "wonderwall.fullname" . }}-idporten-alerts
  labels:
    {{- include "wonderwall.labels" . | nindent 4 }}
spec:
  groups:
    - name: "wonderwall-idporten"
      rules:
        - alert: Wonderwall sidecars for ID-porten reports a high amount of internal errors
          expr: sum(increase(requests_total{job="nais-system/monitoring-wonderwall", code="500", provider="idporten"}[5m])) > 10
          for: 5m
          annotations:
            summary: Wonderwall has responded with HTTP 500 for a high amount of requests within the last 5 minutes.
            consequence: This probably means that end-users are having trouble with authentication.
            action: |
              * Check the logs for errors: <https://logs.adeo.no/app/r/s/tcZC2>
              * Check DigDir status: <https://status.digdir.no> / <https://testmiljo.status.digdir.no/>
              * Check Aiven Redis (session store) and verify Aiven network connectivity
              * Check with DigDir in [#nav-digdir](https://nav-it.slack.com/archives/C013RTT99G9)
            dashboard_url: "https://monitoring.nais.io/d/wQPQ7uHnz/wonderwall?var-provider=idporten"
          labels:
            severity: critical
            namespace: {{ .Release.Namespace }}
        - alert: Wonderwall SSO server for ID-porten reports a high amount of internal errors
          expr: sum(increase(requests_total{app="wonderwall-idporten", namespace="{{ .Release.Namespace }}", code="500"}[5m])) > 10
          for: 5m
          annotations:
            summary: Wonderwall has responded with HTTP 500 for a high amount of requests within the last 5 minutes.
            consequence: This probably means that end-users are having trouble with authentication.
            action: |
              * Check the logs for errors: <https://logs.adeo.no/app/r/s/rGZsy>
              * Check DigDir status: <https://status.digdir.no> / <https://testmiljo.status.digdir.no/>
              * Check Aiven Redis (session store) and verify Aiven network connectivity
              * Check with DigDir in [#nav-digdir](https://nav-it.slack.com/archives/C013RTT99G9)
            dashboard_url: "https://monitoring.nais.io/d/wQPQ7uHnz/wonderwall?var-provider=idporten&var-namespace=nais-system"
          labels:
            severity: critical
            namespace: {{ .Release.Namespace }}
{{ end }}
{{ if .Values.azure.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "wonderwall.fullname" . }}-azure-alerts
  labels:
    {{- include "wonderwall.labels" . | nindent 4 }}
spec:
  groups:
    - name: "wonderwall-azure"
      rules:
        - alert: Wonderwall for Azure AD reports a high amount of internal errors
          expr: sum(increase(requests_total{job="nais-system/monitoring-wonderwall", code="500", provider="azure"}[5m])) > 30
          for: 5m
          annotations:
            summary: Wonderwall has responded with HTTP 500 for a high amount of requests within the last 5 minutes.
            consequence: This probably means that end-users are having trouble with authentication.
            action: |
              * Check the logs for errors: <https://logs.adeo.no/app/r/s/EQy2f>
              * Check Azure status: https://status.azure.com/nb-no/status
              * Check Aiven Redis (session store) and verify Aiven network connectivity
            dashboard_url: "https://monitoring.nais.io/d/wQPQ7uHnz/wonderwall?var-provider=azure"
          labels:
            severity: critical
            namespace: {{ .Release.Namespace }}
        {{- if .Values.azure.forwardAuth.enabled }}
        - alert: Wonderwall-fa (forward-auth / ansatt) for Azure AD reports a high amount of internal errors
          expr: sum(increase(requests_total{app="wonderwall-fa", namespace="{{ .Release.Namespace }}", code="500"}[5m])) > 30
          for: 5m
          annotations:
            summary: Wonderwall has responded with HTTP 500 for a high amount of requests within the last 5 minutes.
            consequence: This probably means that end-users are having trouble with authentication.
            action: |
              * Check the logs for errors: <https://logs.adeo.no/app/r/s/fhBqB>
              * Check Azure status: https://status.azure.com/nb-no/status
              * Check Aiven Redis (session store) and verify Aiven network connectivity
            dashboard_url: "https://monitoring.nais.io/d/wQPQ7uHnz/wonderwall?var-provider=azure&var-namespace=nais-system"
          labels:
            severity: critical
            namespace: {{ .Release.Namespace }}
        {{- end }}
{{ end }}
